### PR TITLE
Add NuttX 12.5.0 release

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Add NuttX 12.5.0 release

## Impact
RELEASE

## Testing
NONE

### CODE REVIEW

**Review by acassis — CHANGES_REQUESTED** [review]
Please release RC1 with blue-pill fix before releasing NuttX 12.5.0

**Comment by jerpelea** [comment]
we will do a 12.5.1 release with blue-pill fix

**Comment by jerpelea** [comment]
please link the fix

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by acassis** [comment]
> please link the fix

https://github.com/apache/nuttx-apps/pull/2344
https://github.com/apache/nuttx/pull/12038

**Comment by jerpelea** [comment]
please merge those release notes so that I can continue with 12.5.1

**Pull request merged**
