### PR TITLE
Added Lup Yuen Lee to contributors

### PR DESCRIPTION
**Pull request by lupyuen**
## Summary

Added myself (Lup Yuen Lee) as PMC and Committer to the list of contributors. Sorry I missed this earlier.

## Impact

Updated the list of contributors.

## Testing

None

### CODE REVIEW

**Review by cederom — APPROVED** [review]
Sure thing Master! :-)

**Comment by cederom** [comment]
One momento sorry @lupyuen.. build fails.. and that is done to update website.. I can see that previous builds also failed and so the website is not updated o_O

@btashton could you please take a look as https://github.com/apache/nuttx-website/actions/runs/4975335982/jobs/8902681849?pr=95? I think https://github.com/apache/nuttx-website/pull/94 did not do the trick.. and there are no special characters now in the username.. and HEAD contains Your commit that also has no special characters in the username.

**Comment by cederom** [comment]
* Can this be caused by GitHub blocking vulnerable ActiveSupport GEM? We have `6.0.6.1.` patched version is `6.1.7.3` and the version 7 is already out. See Security tab at the top (https://github.com/apache/nuttx-website/security/dependabot). On my BSD box I was not able to setup this environment :-(
* Or CI script using node12 instead node16 calls as reported here:
```
build
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

**Comment by cederom** [comment]
Thanks @btashton.. can you see that "All checks have failed" here?

Looking at the "Build Site" part:
```

0s
##[debug]Evaluating condition for step: 'Build Site'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build Site
##[debug]Loading inputs
##[debug]Loading env
Run export GEM_HOME=$HOME/.gem
  export GEM_HOME=$HOME/.gem
  export PATH=$PATH:$GEM_HOME/bin
  username="`git log -1 --pretty=format:'%an'`"
  email="`git log -1 --pretty=format:'%ae'`"
  git config --global user.name $username
  git config --global user.email $email
  ./publish.sh
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.16/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.16/x64/lib
##[debug]/usr/bin/bash -e /home/runner/work/_temp/b2a7b350-874a-4137-b8f2-3d611c0679e3.sh
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    --worktree            use per-worktree config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-pattern]
    --get-all             get all values: key [value-pattern]
    --get-regexp          get values for regexp: name-regex [value-pattern]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value-pattern]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-pattern]
    --unset-all           remove all matches: name [value-pattern]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    --fixed-value         use string equality when comparing values to 'value-pattern'
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    -t, --type <type>     value is given this type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --bool-or-str         value is --bool or string
    --path                value is a path (file or directory name)
    --expiry-date         value is an expiry date

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)
    --show-scope          show scope of config (worktree, local, global, system, command)
    --default <value>     with --get, use default value when missing entry

Error: Process completed with exit code 129.
##[debug]Finishing: Build Site
```

Should I just Merge this one and next checks will use updated scripts?

**Comment by btashton** [comment]
@lupyuen you do not have my change, can you try a rebase so we know if that resolves the issue here?

**Comment by lupyuen** [comment]
Sure I'll rebase later when I'm back at my computer. Thanks everyone :-)

**Comment by cederom** [comment]
Thank you @btashton !! :-)

**Comment by cederom** [comment]
My next PR have "All checks passed" so the fix is working. I will merge this PR now. Thank you for verification @btashton :-)

**Pull request merged**
